name: Deploy to Tomcat

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Pull Docker Image
        run: |
          docker pull rodrigoalcaide/tomcat_image:latest
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      #- name: Create Container
      #  run: |
      #    docker run -d --name tomcat-container -p 8080:8080 rodrigo/tomcat_image:latest

      - name: Docker Run
        uses: tj-actions/docker-run@v2.2.1
        with:
          image: rodrigo/tomcat_image:latest
          name: tomcat-container
          args: -p 8080:8080


      - name: Deploy to Tomcat
        run: |
          docker cp target/JSPSample-0.0.1.war tomcat-container:/usr/local/tomcat/webapps/
        working-directory: ${{ github.workspace }}

      - name: Restart Tomcat
        run: |
          docker restart tomcat-container

